NoCheatPlus compatibility mode: true
Minimal water depth: 1
Enable swimming in creative mode: true
Permissions required: false
Enable while swimming up: true
Enable speed boost/sprinting: true
Sprint speed: 0.3
Enable fall animation: false
Minimal fall distance: 3
Fall glide speed: 0.1
Fall downward speed: 1
Elytra looses durability while swimming: false
EHM_compatibility mode (no speed boost when swimming up): false
Enable stamina: true
Enable drowning when out of stmina: true
Sprint stamina usage: 50
Normal swimming stamina usage: 10
Normal stamina reset time in seconds: 3
Stamina reset time when drowned in seconds: 20
Blink stamina bar when stamina is low: true
Stamina update delay in ticks: 20
Use BossBar to display stamina bar: true
Disable swimming animation in waterfalls: true
Maximum waterfall diameter: 3
Enable armor-weight: true
Max sprinting weight: 20
Warn player when trying to sprint but to heavy: true
Show fullscreen warning when swimming in heavy armor: true
Announce armor weight when starting to swim: true
Diamond Helmet Weight: 10
Diamond Chestplate Weight: 10
Diamond Leggings Weight: 10
Diamond Boots Weight: 10
Iron Helmet Weight: 7
Iron Chestplate Weight: 7
Iron Leggings Weight: 7
Iron Boots Weight: 7
Chain Helmet Weight: 5
Chain Chestplate Weight: 5
Chain Leggings Weight: 5
Chain Boots Weight: 5
Gold Helmet Weight: 6
Gold Chestplate Weight: 6
Gold Leggings Weight: 6
Gold Boots Weight: 6
Leather Helmet Weight: 2
Leather Chestplate Weight: 2
Leather Leggings Weight: 2
Leather Boots Weight: 2
